spring.application.name=demo

# 1. Configuración de la conexión a PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tenis_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:0408}

# 2. Configuración de Hibernate / JPA
# 'update' creará o modificará las tablas automáticamente en pgAdmin según tus clases de Java
spring.jpa.hibernate.ddl-auto=create
# Muestra en la consola las consultas SQL reales que Spring hace por detrás (ideal para aprender y testear)
spring.jpa.show-sql=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:juanperezt89@gmail.com}
spring.mail.password=${MAIL_PASSWORD:uzra omvr nxcq ckfo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true